export const translations = {
  sq: {
    app: {
      title: "Rreziku nga përmbytjet",
      subtitle:
        "Parashikim me model të mësimit makinerik për komunat e Kosovës, me shpjegim të gjeneruar nga OpenAI.",
    },
    language: { label: "Gjuha", sq: "Shqip", en: "English" },
    form: {
      title: "Të dhënat e komunës",
      intro:
        "Formulari është i mbushur me të dhënat e Malishevës si shembull. Ndryshoni çdo vlerë sipas nevojës.",
      municipality: "Komuna",
      municipalityHint: "Opsionale. Përdoret vetëm në shpjegim, jo nga modeli.",
      groups: { terrain: "Terreni", water: "Uji dhe reshjet" },
      soilPlaceholder: "Zgjidhni llojin e tokës",
      submit: "Vlerëso rrezikun",
      submitting: "Duke vlerësuar…",
      reset: "Rikthe të dhënat e Malishevës",
      trainingRange: "Në të dhënat e trajnimit: {min}–{max}",
    },
    features: {
      elevation: "Lartësia mbidetare",
      distance_from_river: "Distanca nga lumi",
      rainfall: "Sasia e reshjeve",
      soil_type: "Lloji i tokës",
      max_water_level: "Niveli maksimal i ujit",
      min_water_level: "Niveli minimal i ujit",
      min_slope: "Pjerrtësia minimale",
      max_slope: "Pjerrtësia maksimale",
    },
    validation: {
      required: "Plotësoni këtë fushë.",
      notNumber: "Shkruani një numër.",
      negative: "Vlera nuk mund të jetë negative.",
      minGreaterThanMax: "Minimumi nuk mund të jetë më i madh se maksimumi.",
      fixFields: "Korrigjoni fushat e shënuara dhe provoni përsëri.",
    },
    risk: { Low: "I ulët", Medium: "Mesatar", High: "I lartë" },
    result: {
      title: "Rezultati",
      emptyTitle: "Ende pa rezultat",
      empty:
        "Shtypni “Vlerëso rrezikun” për të parë parashikimin e modelit për vlerat në formular.",
      riskFor: "Rreziku për {municipality}",
      riskGeneric: "Rreziku i parashikuar",
      gaugeLabel:
        "Matës i nivelit të ujit që tregon rrezikun e parashikuar: {level}",
      votes: "Votat e pemëve të modelit",
      votesNote:
        "Pjesa e pemëve të modelit Random Forest që votuan për secilën klasë. Nuk është probabilitet i përmbytjes.",
      outOfRangeTitle: "Kujdes: vlera jashtë të dhënave të trajnimit",
      outOfRange:
        "{feature}: {value} {unit} është jashtë intervalit {min}–{max} {unit}. Modeli po ekstrapolon, prandaj parashikimi është më pak i besueshëm.",
      model:
        "Modeli: Random Forest. F1 makro me validim të kryqëzuar: {mean} ± {std}.",
    },
    interpretation: {
      title: "Shpjegimi",
      note: "Gjeneruar nga një model gjuhësor (OpenAI) mbi bazën e parashikimit dhe vlerave hyrëse. Nuk është shpjegim shkencor i shkaqeve.",
      disabled:
        "Shpjegimi nuk është i aktivizuar në server. Parashikimi më sipër është i plotë.",
      unavailable:
        "Shpjegimi nuk mund të gjenerohej tani. Parashikimi më sipër mbetet i vlefshëm.",
      rejected:
        "Shpjegimi u hodh poshtë sepse nuk përputhej me klasën e parashikuar nga modeli. Parashikimi mbetet i vlefshëm.",
    },
    limitations: {
      title: "Kufizimet e modelit",
      items: [
        "Modeli është trajnuar vetëm me 38 komuna të Kosovës, prandaj rezultatet kanë pasiguri të lartë.",
        "Klasat e rrezikut janë vlerësim i ekspertit bazuar në të njëjtat të dhëna, jo përmbytje të regjistruara.",
        "Klasa “I ulët” ka vetëm 4 shembuj dhe modeli e njeh dobët; parashikimet “I ulët” janë më pak të besueshme.",
        "Të dhënat e reshjeve dhe të nivelit të ujit janë nga viti 2022 ose 2024, sipas komunës.",
      ],
    },
    errors: {
      unreachable:
        "Serveri nuk përgjigjet në {url}. Kontrolloni që backend-i është duke punuar.",
      metadata: "Të dhënat e modelit nuk u ngarkuan. {detail}",
      server: "Serveri ktheu një gabim: {detail}",
      retry: "Provo përsëri",
    },
  },

  en: {
    app: {
      title: "Flood risk",
      subtitle:
        "Machine-learning prediction for municipalities in Kosovo, with an explanation generated by OpenAI.",
    },
    language: { label: "Language", sq: "Shqip", en: "English" },
    form: {
      title: "Municipality data",
      intro:
        "The form is filled with Malisheva's data as an example. Change any value as needed.",
      municipality: "Municipality",
      municipalityHint:
        "Optional. Used only in the explanation, not by the model.",
      groups: { terrain: "Terrain", water: "Water and rainfall" },
      soilPlaceholder: "Choose a soil type",
      submit: "Assess risk",
      submitting: "Assessing…",
      reset: "Restore Malisheva's data",
      trainingRange: "In the training data: {min}–{max}",
    },
    features: {
      elevation: "Elevation",
      distance_from_river: "Distance from river",
      rainfall: "Rainfall",
      soil_type: "Soil type",
      max_water_level: "Maximum water level",
      min_water_level: "Minimum water level",
      min_slope: "Minimum slope",
      max_slope: "Maximum slope",
    },
    validation: {
      required: "Fill in this field.",
      notNumber: "Enter a number.",
      negative: "The value cannot be negative.",
      minGreaterThanMax: "The minimum cannot be greater than the maximum.",
      fixFields: "Correct the marked fields and try again.",
    },
    risk: { Low: "Low", Medium: "Medium", High: "High" },
    result: {
      title: "Result",
      emptyTitle: "No result yet",
      empty:
        "Press “Assess risk” to see the model's prediction for the values in the form.",
      riskFor: "Risk for {municipality}",
      riskGeneric: "Predicted risk",
      gaugeLabel: "Water level gauge showing the predicted risk: {level}",
      votes: "Model tree votes",
      votesNote:
        "Share of the Random Forest's trees that voted for each class. This is not a probability of flooding.",
      outOfRangeTitle: "Caution: value outside the training data",
      outOfRange:
        "{feature}: {value} {unit} is outside the range {min}–{max} {unit}. The model is extrapolating, so the prediction is less reliable.",
      model: "Model: Random Forest. Cross-validated macro F1: {mean} ± {std}.",
    },
    interpretation: {
      title: "Explanation",
      note: "Generated by a language model (OpenAI) from the prediction and input values. It is not a scientific explanation of causes.",
      disabled:
        "Explanations are not enabled on the server. The prediction above is complete.",
      unavailable:
        "The explanation could not be generated right now. The prediction above is still valid.",
      rejected:
        "The explanation was discarded because it did not match the class predicted by the model. The prediction is still valid.",
    },
    limitations: {
      title: "Model limitations",
      items: [
        "The model was trained on only 38 municipalities in Kosovo, so results are highly uncertain.",
        "Risk classes are an expert assessment based on the same data, not recorded floods.",
        "The Low class has only 4 examples and the model recognises it poorly; Low predictions are less reliable.",
        "Rainfall and water-level data come from 2022 or 2024, depending on the municipality.",
      ],
    },
    errors: {
      unreachable:
        "The server at {url} is not responding. Check that the backend is running.",
      metadata: "The model information could not be loaded. {detail}",
      server: "The server returned an error: {detail}",
      retry: "Try again",
    },
  },
};
